import requests
from bs4 import BeautifulSoup

WORDPRESS_LOGIN = "https://smartmoneymomma.org/wp-login.php"
WORDPRESS_POST_URL = "https://smartmoneymomma.org/wp-admin/post-new.php"

USERNAME = "akhilamadireddy1987@gmail.com"
PASSWORD = "AjahRudhr@2019"

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
}

def login_to_wordpress(session):
    login_payload = {
        'log': USERNAME,
        'pwd': PASSWORD,
        'wp-submit': 'Log In',
        'redirect_to': 'https://smartmoneymomma.org/wp-admin/',
        'testcookie': '1'
    }

    response = session.post(WORDPRESS_LOGIN, headers=HEADERS, data=login_payload)
    return 'dashboard' in response.text.lower()

def publish_post(title, content, tags=None, categories=None):
    with requests.Session() as session:
        if not login_to_wordpress(session):
            print("[ERROR] Failed to login to WordPress.")
            return False

        print("[+] Logged in successfully.")

        # Fetch nonce
        new_post_page = session.get(WORDPRESS_POST_URL)
        soup = BeautifulSoup(new_post_page.text, 'html.parser')
        nonce = soup.find("input", {"id": "_wpnonce"}) or soup.find("input", {"name": "_wpnonce"})
        if not nonce:
            print("[ERROR] Could not find WP nonce token.")
            return False

        post_payload = {
            'post_title': title,
            'content': content,
            '_wpnonce': nonce['value'],
            '_wp_http_referer': '/wp-admin/post-new.php',
            'user_ID': '1',
            'action': 'editpost',
            'originalaction': 'editpost',
            'post_author': '1',
            'post_type': 'post',
            'original_post_status': 'auto-draft',
            'referredby': WORDPRESS_POST_URL,
            'save': 'Publish',
            'post_status': 'publish',
        }

        if tags:
            post_payload['tax_input[post_tag]'] = ','.join(tags)
        if categories:
            for cat in categories:
                post_payload[f"post_category[]"] = cat

        post_response = session.post(
            'https://smartmoneymomma.org/wp-admin/post.php?action=editpost',
            headers=HEADERS,
            data=post_payload
        )

        if "Post published" in post_response.text:
            print("[✓] Post published successfully.")
            return True
        else:
            print("[ERROR] Failed to publish post.")
            return False

if __name__ == "__main__":
    test_title = "Test Post by Eshyel"
    test_content = "This is a test post generated by Eshyel to verify WordPress integration. 💙"
    publish_post(test_title, test_content)

